Ae 92 implement recruiter sign up
Audease/backend-mvp pull request #10
Opened 2024-06-02 19:35 UTC by otimebhor

2024-06-03 09:08 UTC, Mbaoma approved these changes

2024-06-03 10:53 UTC, Tes-program requested changes

2024-06-03 10:53 UTC, Tes-program commented on src/recruiter/recruiter.controller.spec.ts
Where are your tests?

2024-06-03 10:53 UTC, Tes-program commented on src/recruiter/recruiter.controller.ts
Where are the controllers?

2024-06-03 10:53 UTC, Tes-program commented on src/recruiter/recruiter.service.spec.ts
What happened to the tests?

2024-06-03 13:18 UTC, Tes-program requested changes

2024-06-03 13:18 UTC, Tes-program commented on src/auth/auth.service.ts
> +    const admin = await this.userRepository.findOne({
There is already a auth.repository.ts for database methods. I thought we were already clear on using Repository Pattern na?

2024-06-04 05:06 UTC, Tes-program approved these changes

2024-06-08 21:27 UTC, Mbaoma approved these changes

2024-06-12 19:05 UTC, closed without merging